//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dblayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItemDetailTable
    {
        public int OrderItemDetailID { get; set; }
        public int OrderID { get; set; }
        public int StockItemID { get; set; }
        public int Qty { get; set; }
        public double UnitPrice { get; set; }
        public int DiscountID { get; set; }
        public double DiscountAmount { get; set; }
    
        public virtual DiscountTable DiscountTable { get; set; }
        public virtual OrderTable OrderTable { get; set; }
        public virtual StockItemTable StockItemTable { get; set; }
    }
}
